"""
COL_META_COLUMN = 'column'
COL_META_TYPE = 'type'
COL_META_ADDREQ = 'addreq'
META_COLS = [COL_META_COLUMN, COL_META_TYPE, COL_META_ADDREQ]

COL_STOCK_CODE = 'code'
COL_STOCK_NAME = 'name'
COL_DATE = 'date'
COL_DATETIME = 'datetime'
COL_OPEN = 'open'
COL_CLOSE = 'close'
COL_HIGH = 'high'
COL_LOW = 'low'
COL_CHENGJIAOLIANG = 'chengjiaoliang'
COL_CHENGJIAOE = 'chengjiaoe'

STOCK_LIST_TABLE = 'stock_list'
DOWNLOAD_RECORD_TABLE = 'download_record'
TRADE_CALENDAR_TABLE = 'trade_calendar'
STOCK_REALTIME_TABLE = 'stock_realtime'

INT_MAX_VALUE = 2147483647
INT_MIN_VALUE = -2147483648
FLOAT_MAX_VALUE = 3.4028234663852886e+38
FLOAT_MIN_VALUE = -3.4028234663852886e+38


MIN_TRADE_UNIT = 100  # 最小交易单位
"""