#
DATE = "date"
DATETIME = "datetime"
OPEN = "open"
CLOSE = "close"
HIGH = "high"
LOW = "low"
#
CJL = "chengjiaoliang"
CJE = "chengjiaoe"
ZF = "zhenfu"
ZDF = "zhangdiefu"
ZDE = "zhangdiee"
HSL = "huanshoulv"
#
LB = "liangbi"
SYL = "pe"
DSYL = "pettm"
SJL = "pb"
SXL = "ps"
DSXL = "psttm"
GXL = "dv"
DGXL = "dvttm"
ZSZ = "zongshizhi"
LTSZ = "liutongshizhi"
#
FREQ = "freq"
FUQUAN = "fuquan"
SOURCE = "source"
START_DATE = "start_date"
END_DATE = "end_date"
