#
CODE = "code"
NAME = "name"
CONCEPT_CODE = "ccode"
CONCEPT_NAME = "cname"
INDUSTRY_CODE = "icode"
INDUSTRY_NAME = "iname"
INDEX_CODE = "xcode"
INDEX_NAME = "xname"
#
SG = "送股"
ZG = "转股"
SGZG = "送转股合计"
XJ = "现金"
GXL = "股息率"
SY = "每股收益"
JZC = "每股净资产"
GJJ = "每股公积金"
WFP = "每股未分配利润"
LRZZ = "净利润同比增长"
ZGB = "总股本"
GGR = "预案公告日"
DJR = "股权登记日"
CXR = "除权除息日"
JD = "方案进度"
ZXGGR = "最新公告日期"
