COL_META_COLUMN = 'column'
COL_META_TYPE = 'type'
COL_META_ADDREQ = 'addreq'
META_COLS = [COL_META_COLUMN, COL_META_TYPE, COL_META_ADDREQ]

COL_STOCK_CODE = 'code'
COL_STOCK_NAME = 'name'

STOCK_LIST_TABLE = 'stock_list'
DOWN_RECORD_TABLE = 'download_record'
