#
DATE = 'date'
DATETIME = 'datetime'
OPEN = 'open'
CLOSE = 'close'
HIGH = 'high'
LOW = 'low'
#
CJL = 'chengjiaoliang'
CJE = 'chengjiaoe'
ZF = 'zhenfu'
ZDF = 'zhangdiefu'
ZDE = 'zhangdiee'
HSL = 'huanshoulv'
#
FREQ = 'freq'
FUQUAN = 'fuquan'
SOURCE = 'source'
START_DATE = 'start_date'
END_DATE = 'end_date'
